@api = http://localhost:8080

GET {{api}}/events

### GET ONE
GET {{api}}/event/64699b877352de696c9400a6

###
POST {{api}}/new_event
Content-Type: application/json

{
    "name":"Dance Techno",
    "lineup":[
        {
            "name":"Ashley Trumman",
            "pseudo":"Luxury"
        },
        {
            "name":"Abraham Pearce",
            "pseudo":"Pushman"
        }
    ],
    "date":"07/01/2023",
    "location":"La frecuencia violeta",
    "poster":"./public/baumcali.png"
}

###
PUT {{api}}/edit_event/646bd238d0feaaba7cbb3f4b
Content-Type: application/json

{   
    "poster":"./images/baumcali.png"
}

###
DELETE {{api}}/delete_event/646a893d00000bf6d3e9e894
