@api = http://localhost:8080

GET {{api}}/events

###
GET {{api}}/events/past

### GET ONE
GET {{api}}/event/64699b877352de696c9400a6

###
POST {{api}}/new_event
Content-Type: application/json

{

    "name":"Dance Techno",
    "lineup":[
        {
            "name":"Ashley Trumman",
            "pseudo":"Luxury"
        },
        {
            "name":"Abraham Pearce",
            "pseudo":"Pushman"
        }
    ],
    "date":"07/01/2023",
    "location":"La frecuencia violeta",
    "poster":"./public/baumcali.png"
}

###
PUT {{api}}/edit_event/646c55a18dbcdabc63fee811
Content-Type: application/json

{   
    "poster":"http://127.0.0.1:8080/images/Captura de pantalla 2023-05-01 031041.png1684821409758.png"
}

###
DELETE {{api}}/delete/event/64878f9b26073f209924c186

###
DELETE {{api}}/delete/allevents
